---
apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: daily-cluster-backup
  namespace: velero
spec:
  schedule: "0 2 * * *" # Daily at 2 AM
  template:
    includedNamespaces:
      - "*"
    includedResources:
      - "*"
    excludedResources:
      - events
      - pods
    ttl: 168h0m0s # 7 days retention
    storageLocation: default
    volumeSnapshotLocations:
      - longhorn-backup
---
apiVersion: velero.io/v1
kind: BackupStorageLocation
metadata:
  name: longhorn-backup
  namespace: velero
spec:
  provider: aws
  objectStorage:
    bucket: velero
    prefix: longhorn
  credential:
    name: velero-credentials
    key: cloud
  config:
    region: us-east-1
    s3ForcePathStyle: "true"
    s3Url: http://minio.velero.svc.cluster.local:9000
