---
# MinIO for Velero Backup Storage
# Uses NFS PV for persistent storage on Synology NAS
apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio-velero-nfs
  labels:
    app: minio-velero
spec:
  capacity:
    storage: 200Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-minio
  nfs:
    server: 192.168.68.126
    path: /volume2/Proxmox/k8s-backups
  mountOptions:
    - nfsvers=4
    - nolock
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-data
  namespace: velero
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-minio
  resources:
    requests:
      storage: 200Gi
---
apiVersion: v1
kind: Secret
metadata:
  name: minio-credentials
  namespace: velero
type: Opaque
stringData:
  MINIO_ROOT_USER: "minioadmin"
  MINIO_ROOT_PASSWORD: "homelab-backup-2026"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
  namespace: velero
  labels:
    app: minio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minio
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
        - name: minio
          image: minio/minio:RELEASE.2022-10-24T18-35-07Z
          args:
            - server
            - /data
            - --console-address
            - ":9001"
          envFrom:
            - secretRef:
                name: minio-credentials
          ports:
            - containerPort: 9000
              name: api
            - containerPort: 9001
              name: console
          volumeMounts:
            - name: data
              mountPath: /data
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
          livenessProbe:
            httpGet:
              path: /minio/health/live
              port: 9000
            initialDelaySeconds: 30
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /minio/health/ready
              port: 9000
            initialDelaySeconds: 10
            periodSeconds: 10
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: minio-data
---
apiVersion: v1
kind: Service
metadata:
  name: minio
  namespace: velero
spec:
  selector:
    app: minio
  ports:
    - name: api
      port: 9000
      targetPort: 9000
    - name: console
      port: 9001
      targetPort: 9001
---
# Job to create velero bucket on MinIO startup
apiVersion: batch/v1
kind: Job
metadata:
  name: minio-setup
  namespace: velero
spec:
  ttlSecondsAfterFinished: 300
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: mc
          image: minio/mc:RELEASE.2022-10-29T10-09-23Z
          command:
            - /bin/sh
            - -c
            - |
              sleep 15
              mc alias set myminio http://minio.velero.svc.cluster.local:9000 minioadmin homelab-backup-2026
              mc mb --ignore-existing myminio/velero
              mc anonymous set download myminio/velero
              echo "Bucket 'velero' created successfully"
