apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-data
  namespace: velero
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-velero
  resources:
    requests:
      storage: 100Gi
