apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-data
  namespace: velero
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  volumeName: minio-velero-nfs
  resources:
    requests:
      storage: 500Gi
