---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: velero-cleanup
  namespace: velero
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: velero-cleanup
rules:
  - apiGroups:
      - batch
    resources:
      - jobs
    verbs:
      - get
      - list
      - delete
  - apiGroups:
      - velero.io
    resources:
      - backuprepositories
    verbs:
      - get
      - list
      - delete
  - apiGroups:
      - ""
    resources:
      - namespaces
    verbs:
      - get
      - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: velero-cleanup
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: velero-cleanup
subjects:
  - kind: ServiceAccount
    name: velero-cleanup
    namespace: velero
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: velero-cleanup-script
  namespace: velero
data:
  velero-cleanup.sh: |-
    #!/bin/bash
    # Velero Maintenance Cleanup Script
    # Behebt Probleme mit orphaned BackupRepositories von geloeschten Apps

    set -e

    NAMESPACE="velero"
    GRACE_PERIOD_FAILED_JOBS="${1:-3600}"  # Standard: 1h

    echo "=== Velero Cleanup ==="

    # 1. Fehlgeschlagene Maintenance Jobs loeschen
    echo "1. Loeschen fehlgeschlagener Maintenance Jobs..."
    kubectl delete jobs -n $NAMESPACE --field-selector status.successful=0 2>/dev/null || echo "Keine fehlgeschlagenen Jobs gefunden"

    # 2. Orphaned BackupRepositories identifizieren und loeschen
    echo "2. Pruefe auf orphaned BackupRepositories..."
    ORPHANED=$(kubectl get backuprepository -n $NAMESPACE -o json | \
      jq -r '.items[] | select(.metadata.namespace | startswith("kube-system") | not) | .metadata.name' | \
      while read repo; do
        APP_NAME=$(echo $repo | cut -d'-' -f1-2)
        if ! kubectl get ns $APP_NAME &>/dev/null; then
          echo $repo
        fi
      done)

    if [ -z "$ORPHANED" ]; then
      echo "Keine orphaned BackupRepositories gefunden"
    else
      echo "Folgende BackupRepositories werden geloescht:"
      echo "$ORPHANED"
      echo "$ORPHANED" | xargs -I {} kubectl delete backuprepository -n $NAMESPACE {}
    fi

    # 3. Status Report
    echo ""
    echo "=== Status nach Cleanup ==="
    echo "Verbleibende BackupRepositories:"
    kubectl get backuprepository -n $NAMESPACE --no-headers | wc -l
    echo "Laufende Jobs:"
    kubectl get jobs -n $NAMESPACE --no-headers | wc -l

    echo "Cleanup abgeschlossen"
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: velero-cleanup
  namespace: velero
spec:
  schedule: "0 2 * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 3
  startingDeadlineSeconds: 600
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: velero-cleanup
          restartPolicy: OnFailure
          containers:
            - name: cleanup
              image: bitnami/kubectl:1.30.1
              imagePullPolicy: IfNotPresent
              command:
                - /bin/sh
                - -c
              args:
                - >-
                  apt-get update &&
                  apt-get install -y jq &&
                  chmod +x /scripts/velero-cleanup.sh &&
                  /scripts/velero-cleanup.sh
              volumeMounts:
                - name: cleanup-script
                  mountPath: /scripts
          volumes:
            - name: cleanup-script
              configMap:
                name: velero-cleanup-script
                defaultMode: 0755
