---
# ServiceMonitor for Prometheus to scrape PVE Exporter
# Only scrape from ONE node since all nodes report full cluster status
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: pve-exporter
  namespace: monitoring
  labels:
    app: pve-exporter
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  selector:
    matchLabels:
      app: pve-exporter
  endpoints:
    - port: metrics
      path: /pve
      interval: 60s
      scrapeTimeout: 30s
      params:
        target:
          - 192.168.68.211
        cluster:
          - "1"
      relabelings:
        - action: replace
          sourceLabels: [__param_target]
          targetLabel: instance
        - action: replace
          targetLabel: pve_host
          replacement: pve1
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-dashboard-proxmox
  namespace: monitoring
  labels:
    grafana_dashboard: "1"
  annotations:
    argocd.argoproj.io/sync-wave: "10"
    grafana_folder: "Homelab"
data:
  proxmox-cluster.json: |
    {
      "annotations": { "list": [] },
      "editable": true,
      "fiscalYearStartMonth": 0,
      "graphTooltip": 1,
      "id": null,
      "links": [],
      "liveNow": false,
      "panels": [
        {
          "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
          "id": 100,
          "options": { "content": "# Proxmox VE Cluster - Homelab\n6 Nodes: PVE1, PVE2, PVE3, PVE4, PVE6, PVE7", "mode": "markdown" },
          "title": "",
          "transparent": true,
          "type": "text"
        },
        {
          "datasource": { "type": "prometheus", "uid": "prometheus" },
          "fieldConfig": {
            "defaults": {
              "color": { "mode": "thresholds" },
              "mappings": [{ "options": { "0": { "color": "red", "text": "Offline" }, "1": { "color": "green", "text": "Online" } }, "type": "value" }],
              "thresholds": { "mode": "absolute", "steps": [{ "color": "red", "value": null }, { "color": "green", "value": 1 }] }
            }
          },
          "gridPos": { "h": 3, "w": 4, "x": 0, "y": 2 },
          "id": 1,
          "options": { "colorMode": "background", "graphMode": "none", "justifyMode": "auto", "orientation": "horizontal", "reduceOptions": { "calcs": ["lastNotNull"], "fields": "", "values": false } },
          "title": "PVE1",
          "type": "stat",
          "targets": [{ "expr": "max(pve_up{id=\"node/pve1\"})", "refId": "A" }]
        },
        {
          "datasource": { "type": "prometheus", "uid": "prometheus" },
          "fieldConfig": {
            "defaults": {
              "color": { "mode": "thresholds" },
              "mappings": [{ "options": { "0": { "color": "red", "text": "Offline" }, "1": { "color": "green", "text": "Online" } }, "type": "value" }],
              "thresholds": { "mode": "absolute", "steps": [{ "color": "red", "value": null }, { "color": "green", "value": 1 }] }
            }
          },
          "gridPos": { "h": 3, "w": 4, "x": 4, "y": 2 },
          "id": 2,
          "options": { "colorMode": "background", "graphMode": "none", "justifyMode": "auto", "orientation": "horizontal", "reduceOptions": { "calcs": ["lastNotNull"], "fields": "", "values": false } },
          "title": "PVE2",
          "type": "stat",
          "targets": [{ "expr": "max(pve_up{id=\"node/pve2\"})", "refId": "A" }]
        },
        {
          "datasource": { "type": "prometheus", "uid": "prometheus" },
          "fieldConfig": {
            "defaults": {
              "color": { "mode": "thresholds" },
              "mappings": [{ "options": { "0": { "color": "red", "text": "Offline" }, "1": { "color": "green", "text": "Online" } }, "type": "value" }],
              "thresholds": { "mode": "absolute", "steps": [{ "color": "red", "value": null }, { "color": "green", "value": 1 }] }
            }
          },
          "gridPos": { "h": 3, "w": 4, "x": 8, "y": 2 },
          "id": 3,
          "options": { "colorMode": "background", "graphMode": "none", "justifyMode": "auto", "orientation": "horizontal", "reduceOptions": { "calcs": ["lastNotNull"], "fields": "", "values": false } },
          "title": "PVE3",
          "type": "stat",
          "targets": [{ "expr": "max(pve_up{id=\"node/pve3\"})", "refId": "A" }]
        },
        {
          "datasource": { "type": "prometheus", "uid": "prometheus" },
          "fieldConfig": {
            "defaults": {
              "color": { "mode": "thresholds" },
              "mappings": [{ "options": { "0": { "color": "red", "text": "Offline" }, "1": { "color": "green", "text": "Online" } }, "type": "value" }],
              "thresholds": { "mode": "absolute", "steps": [{ "color": "red", "value": null }, { "color": "green", "value": 1 }] }
            }
          },
          "gridPos": { "h": 3, "w": 4, "x": 12, "y": 2 },
          "id": 4,
          "options": { "colorMode": "background", "graphMode": "none", "justifyMode": "auto", "orientation": "horizontal", "reduceOptions": { "calcs": ["lastNotNull"], "fields": "", "values": false } },
          "title": "PVE4",
          "type": "stat",
          "targets": [{ "expr": "max(pve_up{id=\"node/pve4\"})", "refId": "A" }]
        },
        {
          "datasource": { "type": "prometheus", "uid": "prometheus" },
          "fieldConfig": {
            "defaults": {
              "color": { "mode": "thresholds" },
              "mappings": [{ "options": { "0": { "color": "red", "text": "Offline" }, "1": { "color": "green", "text": "Online" } }, "type": "value" }],
              "thresholds": { "mode": "absolute", "steps": [{ "color": "red", "value": null }, { "color": "green", "value": 1 }] }
            }
          },
          "gridPos": { "h": 3, "w": 4, "x": 16, "y": 2 },
          "id": 5,
          "options": { "colorMode": "background", "graphMode": "none", "justifyMode": "auto", "orientation": "horizontal", "reduceOptions": { "calcs": ["lastNotNull"], "fields": "", "values": false } },
          "title": "PVE6",
          "type": "stat",
          "targets": [{ "expr": "max(pve_up{id=\"node/pve6\"})", "refId": "A" }]
        },
        {
          "datasource": { "type": "prometheus", "uid": "prometheus" },
          "fieldConfig": {
            "defaults": {
              "color": { "mode": "thresholds" },
              "mappings": [{ "options": { "0": { "color": "red", "text": "Offline" }, "1": { "color": "green", "text": "Online" } }, "type": "value" }],
              "thresholds": { "mode": "absolute", "steps": [{ "color": "red", "value": null }, { "color": "green", "value": 1 }] }
            }
          },
          "gridPos": { "h": 3, "w": 4, "x": 20, "y": 2 },
          "id": 6,
          "options": { "colorMode": "background", "graphMode": "none", "justifyMode": "auto", "orientation": "horizontal", "reduceOptions": { "calcs": ["lastNotNull"], "fields": "", "values": false } },
          "title": "PVE7",
          "type": "stat",
          "targets": [{ "expr": "max(pve_up{id=\"node/pve7\"})", "refId": "A" }]
        },
        {
          "datasource": { "type": "prometheus", "uid": "prometheus" },
          "fieldConfig": {
            "defaults": {
              "color": { "mode": "palette-classic" },
              "custom": { "axisCenteredZero": false, "axisColorMode": "text", "axisPlacement": "auto", "barAlignment": 0, "drawStyle": "line", "fillOpacity": 20, "gradientMode": "none", "lineInterpolation": "smooth", "lineWidth": 2, "pointSize": 5, "scaleDistribution": { "type": "linear" }, "showPoints": "never", "spanNulls": false, "stacking": { "group": "A", "mode": "none" }, "thresholdsStyle": { "mode": "off" } },
              "mappings": [],
              "max": 100,
              "min": 0,
              "thresholds": { "mode": "absolute", "steps": [{ "color": "green", "value": null }, { "color": "yellow", "value": 70 }, { "color": "red", "value": 90 }] },
              "unit": "percent"
            }
          },
          "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
          "id": 10,
          "options": { "legend": { "calcs": ["mean", "max"], "displayMode": "table", "placement": "right" }, "tooltip": { "mode": "multi", "sort": "desc" } },
          "title": "CPU Usage per Node",
          "type": "timeseries",
          "targets": [{ "expr": "max by(id) (pve_cpu_usage_ratio{id=~\"node/.*\"}) * 100", "legendFormat": "{{id}}", "refId": "A" }]
        },
        {
          "datasource": { "type": "prometheus", "uid": "prometheus" },
          "fieldConfig": {
            "defaults": {
              "color": { "mode": "palette-classic" },
              "custom": { "axisCenteredZero": false, "axisColorMode": "text", "axisPlacement": "auto", "barAlignment": 0, "drawStyle": "line", "fillOpacity": 20, "gradientMode": "none", "lineInterpolation": "smooth", "lineWidth": 2, "pointSize": 5, "scaleDistribution": { "type": "linear" }, "showPoints": "never", "spanNulls": false, "stacking": { "group": "A", "mode": "none" }, "thresholdsStyle": { "mode": "off" } },
              "mappings": [],
              "max": 100,
              "min": 0,
              "thresholds": { "mode": "absolute", "steps": [{ "color": "green", "value": null }, { "color": "yellow", "value": 70 }, { "color": "red", "value": 90 }] },
              "unit": "percent"
            }
          },
          "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
          "id": 11,
          "options": { "legend": { "calcs": ["mean", "max"], "displayMode": "table", "placement": "right" }, "tooltip": { "mode": "multi", "sort": "desc" } },
          "title": "Memory Usage per Node",
          "type": "timeseries",
          "targets": [{ "expr": "(max by(id) (pve_memory_usage_bytes{id=~\"node/.*\"}) / max by(id) (pve_memory_size_bytes{id=~\"node/.*\"})) * 100", "legendFormat": "{{id}}", "refId": "A" }]
        },
        {
          "datasource": { "type": "prometheus", "uid": "prometheus" },
          "fieldConfig": { "defaults": { "color": { "mode": "thresholds" }, "mappings": [], "thresholds": { "mode": "absolute", "steps": [{ "color": "green", "value": null }] } } },
          "gridPos": { "h": 4, "w": 6, "x": 0, "y": 13 },
          "id": 20,
          "options": { "colorMode": "value", "graphMode": "none", "justifyMode": "auto", "orientation": "auto", "reduceOptions": { "calcs": ["lastNotNull"], "fields": "", "values": false } },
          "title": "Total VMs",
          "type": "stat",
          "targets": [{ "expr": "count(max by(id) (pve_guest_info{id=~\"qemu/.*\"}))", "refId": "A" }]
        },
        {
          "datasource": { "type": "prometheus", "uid": "prometheus" },
          "fieldConfig": { "defaults": { "color": { "mode": "thresholds" }, "mappings": [], "thresholds": { "mode": "absolute", "steps": [{ "color": "green", "value": null }] } } },
          "gridPos": { "h": 4, "w": 6, "x": 6, "y": 13 },
          "id": 21,
          "options": { "colorMode": "value", "graphMode": "none", "justifyMode": "auto", "orientation": "auto", "reduceOptions": { "calcs": ["lastNotNull"], "fields": "", "values": false } },
          "title": "Running VMs",
          "type": "stat",
          "targets": [{ "expr": "count(max by(id) (pve_up{id=~\"qemu/.*\"}) == 1)", "refId": "A" }]
        },
        {
          "datasource": { "type": "prometheus", "uid": "prometheus" },
          "fieldConfig": { "defaults": { "color": { "mode": "thresholds" }, "mappings": [], "thresholds": { "mode": "absolute", "steps": [{ "color": "green", "value": null }] } } },
          "gridPos": { "h": 4, "w": 6, "x": 12, "y": 13 },
          "id": 22,
          "options": { "colorMode": "value", "graphMode": "none", "justifyMode": "auto", "orientation": "auto", "reduceOptions": { "calcs": ["lastNotNull"], "fields": "", "values": false } },
          "title": "Total LXC",
          "type": "stat",
          "targets": [{ "expr": "count(max by(id) (pve_guest_info{id=~\"lxc/.*\"}))", "refId": "A" }]
        },
        {
          "datasource": { "type": "prometheus", "uid": "prometheus" },
          "fieldConfig": { "defaults": { "color": { "mode": "thresholds" }, "mappings": [], "thresholds": { "mode": "absolute", "steps": [{ "color": "green", "value": null }] } } },
          "gridPos": { "h": 4, "w": 6, "x": 18, "y": 13 },
          "id": 23,
          "options": { "colorMode": "value", "graphMode": "none", "justifyMode": "auto", "orientation": "auto", "reduceOptions": { "calcs": ["lastNotNull"], "fields": "", "values": false } },
          "title": "Running LXC",
          "type": "stat",
          "targets": [{ "expr": "count(max by(id) (pve_up{id=~\"lxc/.*\"}) == 1)", "refId": "A" }]
        },
        {
          "datasource": { "type": "prometheus", "uid": "prometheus" },
          "fieldConfig": {
            "defaults": {
              "color": { "mode": "palette-classic" },
              "custom": { "axisCenteredZero": false, "axisColorMode": "text", "axisPlacement": "auto", "barAlignment": 0, "drawStyle": "line", "fillOpacity": 20, "gradientMode": "none", "lineInterpolation": "smooth", "lineWidth": 2, "pointSize": 5, "scaleDistribution": { "type": "linear" }, "showPoints": "never", "spanNulls": false, "stacking": { "group": "A", "mode": "none" }, "thresholdsStyle": { "mode": "off" } },
              "mappings": [],
              "thresholds": { "mode": "absolute", "steps": [{ "color": "green", "value": null }] },
              "unit": "bytes"
            }
          },
          "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
          "id": 30,
          "options": { "legend": { "calcs": ["lastNotNull"], "displayMode": "table", "placement": "right" }, "tooltip": { "mode": "multi", "sort": "desc" } },
          "title": "Memory per Node (Used / Total)",
          "type": "timeseries",
          "targets": [
            { "expr": "max by(id) (pve_memory_usage_bytes{id=~\"node/.*\"})", "legendFormat": "{{id}} Used", "refId": "A" },
            { "expr": "max by(id) (pve_memory_size_bytes{id=~\"node/.*\"})", "legendFormat": "{{id}} Total", "refId": "B" }
          ]
        },
        {
          "datasource": { "type": "prometheus", "uid": "prometheus" },
          "fieldConfig": {
            "defaults": {
              "color": { "mode": "palette-classic" },
              "custom": { "axisCenteredZero": false, "axisColorMode": "text", "axisPlacement": "auto", "barAlignment": 0, "drawStyle": "line", "fillOpacity": 20, "gradientMode": "none", "lineInterpolation": "smooth", "lineWidth": 2, "pointSize": 5, "scaleDistribution": { "type": "linear" }, "showPoints": "never", "spanNulls": false, "stacking": { "group": "A", "mode": "none" }, "thresholdsStyle": { "mode": "off" } },
              "mappings": [],
              "max": 100,
              "min": 0,
              "thresholds": { "mode": "absolute", "steps": [{ "color": "green", "value": null }, { "color": "yellow", "value": 70 }, { "color": "red", "value": 90 }] },
              "unit": "percent"
            }
          },
          "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
          "id": 31,
          "options": { "legend": { "calcs": ["mean", "max"], "displayMode": "table", "placement": "right" }, "tooltip": { "mode": "multi", "sort": "desc" } },
          "title": "Local Storage Usage",
          "type": "timeseries",
          "targets": [{ "expr": "(max by(id) (pve_disk_usage_bytes{id=~\"storage/.*/local.*\"}) / max by(id) (pve_disk_size_bytes{id=~\"storage/.*/local.*\"})) * 100", "legendFormat": "{{id}}", "refId": "A" }]
        },
        {
          "datasource": { "type": "prometheus", "uid": "prometheus" },
          "fieldConfig": {
            "defaults": { "color": { "mode": "thresholds" }, "custom": { "align": "auto", "cellOptions": { "type": "auto" }, "inspect": false }, "mappings": [], "thresholds": { "mode": "absolute", "steps": [{ "color": "green", "value": null }] } },
            "overrides": [
              { "matcher": { "id": "byName", "options": "Name" }, "properties": [{ "id": "custom.width", "value": 200 }] },
              { "matcher": { "id": "byName", "options": "Status" }, "properties": [{ "id": "mappings", "value": [{ "options": { "0": { "color": "red", "text": "Stopped" }, "1": { "color": "green", "text": "Running" } }, "type": "value" }] }, { "id": "custom.cellOptions", "value": { "type": "color-background" } }, { "id": "custom.width", "value": 80 }] },
              { "matcher": { "id": "byName", "options": "CPU %" }, "properties": [{ "id": "unit", "value": "percent" }, { "id": "custom.cellOptions", "value": { "mode": "gradient", "type": "gauge" } }, { "id": "max", "value": 100 }, { "id": "custom.width", "value": 150 }] },
              { "matcher": { "id": "byName", "options": "Mem %" }, "properties": [{ "id": "unit", "value": "percent" }, { "id": "custom.cellOptions", "value": { "mode": "gradient", "type": "gauge" } }, { "id": "max", "value": 100 }, { "id": "custom.width", "value": 150 }] },
              { "matcher": { "id": "byName", "options": "Node" }, "properties": [{ "id": "custom.width", "value": 60 }] },
              { "matcher": { "id": "byName", "options": "ID" }, "properties": [{ "id": "custom.width", "value": 80 }] }
            ]
          },
          "gridPos": { "h": 12, "w": 24, "x": 0, "y": 25 },
          "id": 40,
          "options": { "footer": { "enablePagination": true, "fields": "", "reducer": ["sum"], "show": false }, "showHeader": true, "sortBy": [{ "desc": false, "displayName": "Name" }] },
          "title": "VM & Container List",
          "type": "table",
          "targets": [
            { "expr": "max by(id, name, node) (pve_guest_info)", "format": "table", "instant": true, "refId": "info" },
            { "expr": "max by(id) (pve_up{id=~\"(qemu|lxc)/.*\"})", "format": "table", "instant": true, "refId": "status" },
            { "expr": "max by(id) (pve_cpu_usage_ratio{id=~\"(qemu|lxc)/.*\"}) * 100", "format": "table", "instant": true, "refId": "cpu" },
            { "expr": "(max by(id) (pve_memory_usage_bytes{id=~\"(qemu|lxc)/.*\"}) / max by(id) (pve_memory_size_bytes{id=~\"(qemu|lxc)/.*\"})) * 100", "format": "table", "instant": true, "refId": "mem" }
          ],
          "transformations": [
            { "id": "seriesToColumns", "options": { "byField": "id" } },
            { "id": "organize", "options": { "excludeByName": { "Time": true, "Time 1": true, "Time 2": true, "Time 3": true, "Time 4": true, "__name__": true, "__name__ 1": true, "__name__ 2": true, "__name__ 3": true, "cluster": true, "instance": true, "job": true, "pve_host": true, "template": true, "Value #info": true }, "indexByName": { "Name": 0, "Status": 1, "Node": 2, "CPU %": 3, "Mem %": 4, "ID": 5 }, "renameByName": { "Value #cpu": "CPU %", "Value #mem": "Mem %", "Value #status": "Status", "id": "ID", "name": "Name", "node": "Node" } } }
          ]
        }
      ],
      "refresh": "30s",
      "schemaVersion": 38,
      "style": "dark",
      "tags": ["proxmox", "homelab", "virtualization"],
      "templating": { "list": [] },
      "time": { "from": "now-1h", "to": "now" },
      "timepicker": {},
      "timezone": "browser",
      "title": "Proxmox VE Cluster",
      "uid": "proxmox-cluster",
      "version": 1,
      "weekStart": ""
    }
