---
# ServiceMonitor for Prometheus to scrape PVE Exporter
# Only scrape from ONE node since all nodes report full cluster status
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: pve-exporter
  namespace: monitoring
  labels:
    app: pve-exporter
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  selector:
    matchLabels:
      app: pve-exporter
  endpoints:
    - port: metrics
      path: /pve
      interval: 60s
      scrapeTimeout: 30s
      params:
        target:
          - 192.168.68.211
        cluster:
          - "1"
      relabelings:
        - action: replace
          sourceLabels: [__param_target]
          targetLabel: instance
        - action: replace
          targetLabel: pve_host
          replacement: pve1
