---
# Loki Stack - Log aggregation with Promtail
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki-stack
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: loki-stack
    targetRevision: 2.10.2
    helm:
      releaseName: loki
      values: |
        # Loki configuration
        loki:
          enabled: true
          readinessProbe:
            failureThreshold: 10
            initialDelaySeconds: 45  # Give Loki more time to start
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
          livenessProbe:
            failureThreshold: 10
            initialDelaySeconds: 60
            periodSeconds: 15
            successThreshold: 1
            timeoutSeconds: 5
          persistence:
            enabled: true
            storageClassName: longhorn
            size: 20Gi
          config:
            auth_enabled: false
            server:
              http_listen_port: 3100
            ingester:
              lifecycler:
                ring:
                  kvstore:
                    store: inmemory
                  replication_factor: 1
              chunk_idle_period: 3m
              chunk_block_size: 262144
              chunk_retain_period: 1m
              max_transfer_retries: 0
            schema_config:
              configs:
                - from: 2020-10-24
                  store: boltdb-shipper
                  object_store: filesystem
                  schema: v11
                  index:
                    prefix: index_
                    period: 24h
            storage_config:
              boltdb_shipper:
                active_index_directory: /data/loki/boltdb-shipper-active
                cache_location: /data/loki/boltdb-shipper-cache
                cache_ttl: 24h
                shared_store: filesystem
              filesystem:
                directory: /data/loki/chunks
            limits_config:
              enforce_metric_name: false
              reject_old_samples: true
              reject_old_samples_max_age: 168h
              ingestion_rate_mb: 16
              ingestion_burst_size_mb: 24
              max_streams_per_user: 10000
            chunk_store_config:
              max_look_back_period: 0s
            table_manager:
              retention_deletes_enabled: true
              retention_period: 720h  # 30 days
            compactor:
              working_directory: /data/loki/compactor
              shared_store: filesystem
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi

        # Promtail - Log collector (DaemonSet)
        promtail:
          enabled: true
          readinessProbe:
            failureThreshold: 5
            initialDelaySeconds: 30  # Wait 30s before first health check
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
          livenessProbe:
            failureThreshold: 10
            initialDelaySeconds: 60  # Wait 60s before liveness check
            periodSeconds: 15
            successThreshold: 1
            timeoutSeconds: 5
          config:
            serverPort: 3101
            lokiAddress: http://loki:3100/loki/api/v1/push
            snippets:
              pipelineStages:
                - cri: {}
              scrapeConfigs: |
                # Kubernetes pods
                - job_name: kubernetes-pods
                  pipeline_stages:
                    {{- toYaml .Values.config.snippets.pipelineStages | nindent 4 }}
                  kubernetes_sd_configs:
                    - role: pod
                  relabel_configs:
                    - source_labels:
                        - __meta_kubernetes_pod_controller_name
                      regex: ([0-9a-z-.]+?)(-[0-9a-f]{8,10})?
                      action: replace
                      target_label: __tmp_controller_name
                    - source_labels:
                        - __meta_kubernetes_pod_label_app_kubernetes_io_name
                        - __meta_kubernetes_pod_label_app
                        - __tmp_controller_name
                        - __meta_kubernetes_pod_name
                      regex: ^;*([^;]+)(;.*)?$
                      action: replace
                      target_label: app
                    - source_labels:
                        - __meta_kubernetes_pod_label_app_kubernetes_io_instance
                        - __meta_kubernetes_pod_label_release
                      regex: ^;*([^;]+)(;.*)?$
                      action: replace
                      target_label: instance
                    - source_labels:
                        - __meta_kubernetes_pod_label_app_kubernetes_io_component
                        - __meta_kubernetes_pod_label_component
                      regex: ^;*([^;]+)(;.*)?$
                      action: replace
                      target_label: component
                    - action: replace
                      source_labels:
                        - __meta_kubernetes_pod_node_name
                      target_label: node_name
                    - action: replace
                      source_labels:
                        - __meta_kubernetes_namespace
                      target_label: namespace
                    - action: replace
                      replacement: $1
                      separator: /
                      source_labels:
                        - namespace
                        - app
                      target_label: job
                    - action: replace
                      source_labels:
                        - __meta_kubernetes_pod_name
                      target_label: pod
                    - action: replace
                      source_labels:
                        - __meta_kubernetes_pod_container_name
                      target_label: container
                    - action: replace
                      replacement: /var/log/pods/*$1/*.log
                      separator: /
                      source_labels:
                        - __meta_kubernetes_pod_uid
                        - __meta_kubernetes_pod_container_name
                      target_label: __path__
                    - action: replace
                      regex: true/(.*)
                      replacement: /var/log/pods/*$1/*.log
                      separator: /
                      source_labels:
                        - __meta_kubernetes_pod_annotationpresent_kubernetes_io_config_hash
                        - __meta_kubernetes_pod_annotation_kubernetes_io_config_hash
                        - __meta_kubernetes_pod_container_name
                      target_label: __path__
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 256Mi

        # Disable Grafana (using kube-prometheus-stack's Grafana)
        grafana:
          enabled: false

        # Disable Prometheus (using kube-prometheus-stack)
        prometheus:
          enabled: false

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
