apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rancher
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://releases.rancher.com/server-charts/stable
    targetRevision: 2.13.1
    chart: rancher
    helm:
      skipCrds: false
      values: |
        hostname: rancher.lab.samuelgesang.de
        ingress:
          enabled: true
          ingressClassName: nginx
          tls:
            source: letsEncrypt
          extraAnnotations:
            nginx.ingress.kubernetes.io/ssl-redirect: "false"
            nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
        letsEncrypt:
          email: sgesang@mailo.com
          ingress:
            class: nginx
  destination:
    server: https://kubernetes.default.svc
    namespace: cattle-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  ignoreDifferences:
    - group: networking.k8s.io
      kind: Ingress
      jsonPointers:
        - /spec/tls
