---
# NFS PersistentVolume für eBook-Bibliothek
apiVersion: v1
kind: PersistentVolume
metadata:
  name: calibre-nfs-library
spec:
  capacity:
    storage: 500Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.68.126
    path: /volume1/Privat/WISSEN
  mountOptions:
    - nfsvers=3
    - hard
    - timeo=600
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: calibre-nfs-library
  namespace: calibre
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 500Gi
  volumeName: calibre-nfs-library
---
# Lokaler Storage für Calibre-Datenbank und Config
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: calibre-data
  namespace: calibre
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 10Gi
