---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: netbox-secrets
  namespace: netbox
spec:
  encryptedData:
    SECRET_KEY: AgCFvQWwSumBXYZeIDJki636yBi4LxMlgpK/A/OilSWB+5sMh+8LlTVyvl7fOlpJQ36Dc6IPSzYVSsJuLKejor6Q7Y2FpHnNNVqg34Y3g7vHProXckWR13y1rGt1/jiejg1kzXGcHSODX3CblMgclMJfpbWcjX39QRQSWNEk4ErV2F5dlskZJOj5Bz1i1/32p/bJOL889cZFEfQtSJgcNjIRHK29YHsHmcY3/3HYJ2nFXpidNPtvwlWclfFDu4nDo0xnpTo2Ib+rC2cwhQNKnI8q3KyMw608s21derLPgkoGOoBUTtXG/Q+AmVXThrGFumha3CuFEKTkWG//y1ghZ35sPndsbK4QKBfRF+BHsd3Y4RxW7erzJI+B7tQ2D6Y5HdmswCiSrNfCr++Djoa4OLE37Xd04mRivQyYBTZxwNL/q4Bu7koSFtaGwt41VbWyWdz1beFtYlX5oH8vo+cgMa7G6x6VJlIU8bboyU9wt8/ZHP11s/1Tu8LUbSTL1C8uUDpj7pBVn0D9Eu+v03ZLIIbo8MgXBpceOZfQ8G5BqHtDZEG0HSykDklmhFCCyU2USu4gUNjlr02Mzb5NUHKQdGmCiv9JX8cPhJsLmS70CMcnmSmNZ7ANqHyCq718icwqHMBrmUQALn9s342562wPBMmyd2i/VgGXFFyA+lQcEHqUH0RFdmFpwmDIjABR1sMkrFaxQuhfubBCR6PN3gy3TvcEJOwquiThs9sBJRFb3jacEj9f+9FRQyeyHWoQL149cZuyR9jov4/9BbRzgnrfuUbEKqrzLsZyjWw=
  template:
    metadata:
      annotations:
        argocd.argoproj.io/tracking-id: netbox:/Secret:netbox/netbox-secrets
      name: netbox-secrets
      namespace: netbox
    type: Opaque
