apiVersion: batch/v1
kind: CronJob
metadata:
  name: kavita-mount-fix
  namespace: kavita
spec:
  schedule: "*/15 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: kavita-mount-fix
          containers:
            - name: mount-fix
              image: bitnami/kubectl:latest
              command:
                - /bin/bash
                - -c
                - |
                  set -e
                  # Sicherheit: Niemals PVCs löschen!
                  # Das Skript löscht ausschließlich VolumeAttachment-Objekte und Pods.
                  for pod in $(kubectl get pods -n kavita --field-selector=status.phase=Pending -o jsonpath='{.items[*].metadata.name}'); do
                    if kubectl describe pod -n kavita "$pod" | grep -q 'already mounted or mount point busy'; then
                      echo "Mount-Fehler bei Pod $pod erkannt. Versuche zugehörige VolumeAttachments zu finden und zu löschen."
                      # Alle PVCs, die im Pod gemountet werden sollen, extrahieren
                      for pvc in $(kubectl get pod -n kavita "$pod" -o jsonpath='{.spec.volumes[*].persistentVolumeClaim.claimName}'); do
                        # Die zugehörige PV finden
                        pv=$(kubectl get pvc "$pvc" -n kavita -o jsonpath='{.spec.volumeName}')
                        if [ -n "$pv" ]; then
                          # VolumeAttachment für diese PV suchen
                          VA=$(kubectl get volumeattachments.storage.k8s.io --no-headers | grep "$pv" | awk '{print $1}')
                          if [ -n "$VA" ]; then
                            echo "Lösche VolumeAttachment $VA für PV $pv (PVC $pvc)"
                            kubectl delete volumeattachment "$VA"
                          fi
                        fi
                      done
                      kubectl delete pod -n kavita "$pod"
                    fi
                  done
          restartPolicy: OnFailure
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kavita-mount-fix
  namespace: kavita
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kavita-mount-fix
  namespace: kavita
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "delete", "describe"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["volumeattachments"]
    verbs: ["get", "list", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kavita-mount-fix
  namespace: kavita
subjects:
  - kind: ServiceAccount
    name: kavita-mount-fix
    namespace: kavita
roleRef:
  kind: Role
  name: kavita-mount-fix
  apiGroup: rbac.authorization.k8s.io
